export enum VkProcess {
  NOTIFICATION = 'NOTIFICATION',
  UPDATE_AVATAR = 'UPDATE_AVATAR',
  MINI_APP_PUSH = 'MINI_APP_PUSH',
  MINI_APP_CHECK_PUSH_PERMISSIONS = 'MINI_APP_CHECK_PUSH_PERMISSIONS',
}
